// Standalone HTML export: serializes the rendered report into a
// self-contained document with inlined theme CSS.
const THEME_CSS = `
  :root { color-scheme: light; }
  body { font-family: 'Inter', system-ui, sans-serif; color: #171a2b; background: #ffffff; margin: 40px auto; max-width: 900px; padding: 0 24px; line-height: 1.55; }
  h1, h2, h3 { font-family: Georgia, serif; color: #232a4d; }
  .card { border: 1px solid rgba(24,30,66,0.12); border-radius: 14px; padding: 18px; margin: 14px 0; page-break-inside: avoid; }
  .chip { display: inline-block; border: 1px solid rgba(24,30,66,0.15); border-radius: 999px; padding: 2px 10px; font-size: 12px; color: #464c66; background: #eef0f7; }
  .muted { color: #464c66; } .dim { color: #737a94; }
  .label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #737a94; }
  a { color: #2a5fc4; }
  button, nav, input, select, textarea, summary::marker { display: none; }
  details { display: block; } details > * { display: block; }
  svg { max-width: 100%; }
  @media print { body { margin: 10mm; } }
`

export function exportElementAsHtml(element: HTMLElement, title: string) {
  const clone = element.cloneNode(true) as HTMLElement
  // Open all collapsed sections in the export
  clone.querySelectorAll('details').forEach((d) => d.setAttribute('open', ''))
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title.replace(/</g, '&lt;')}</title>
<style>${THEME_CSS}</style>
</head>
<body>
<h1>${title.replace(/</g, '&lt;')}</h1>
<p class="dim">Generated by Constellation · ${new Date().toLocaleString()}</p>
${clone.outerHTML}
</body>
</html>`
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${title.slice(0, 60).replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.html`
  a.click()
  URL.revokeObjectURL(url)
}
